name: task_management_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  ionicons: 0.1.2
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.2
  google_sign_in: ^5.4.1
  firebase_auth_web: 4.2.3
  cloud_firestore: 3.4.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/Images/
    - assets/Icons/
  uses-material-design: true

