// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkc8Kwyuh-faHM8eJEzrRG-60Hrae9xUg',
    appId: '1:206372425201:web:c54448ecc9314fa0fac850',
    messagingSenderId: '206372425201',
    projectId: 'task-management-apps-542cd',
    authDomain: 'task-management-apps-542cd.firebaseapp.com',
    storageBucket: 'task-management-apps-542cd.appspot.com',
    measurementId: 'G-LFPYXCBWPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQzhz6cBpDqmK8WHOBU1Q-gfc1THTqgm8',
    appId: '1:206372425201:android:2fc7a0f87efea9acfac850',
    messagingSenderId: '206372425201',
    projectId: 'task-management-apps-542cd',
    storageBucket: 'task-management-apps-542cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDJzCH8fc-X6SubuFRKdEkSh4t-Gj3H6I',
    appId: '1:206372425201:ios:72cc080ae0a337e3fac850',
    messagingSenderId: '206372425201',
    projectId: 'task-management-apps-542cd',
    storageBucket: 'task-management-apps-542cd.appspot.com',
    androidClientId: '206372425201-j57pmb13oqeci28eov2c4ncpdta11i1r.apps.googleusercontent.com',
    iosClientId: '206372425201-2a5hjmlf5ou7somh6jgpcreo5p4b70rv.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDJzCH8fc-X6SubuFRKdEkSh4t-Gj3H6I',
    appId: '1:206372425201:ios:72cc080ae0a337e3fac850',
    messagingSenderId: '206372425201',
    projectId: 'task-management-apps-542cd',
    storageBucket: 'task-management-apps-542cd.appspot.com',
    androidClientId: '206372425201-j57pmb13oqeci28eov2c4ncpdta11i1r.apps.googleusercontent.com',
    iosClientId: '206372425201-2a5hjmlf5ou7somh6jgpcreo5p4b70rv.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp',
  );
}
